# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zig_dis_x86_64-0.0.1-bnhOUeE0BABOq-DLv-ADSQ73SeS82ee5rQ00m27yiHp2";
    path = fetchzip {
      url = "https://github.com/bigsaltyfishes/zig-dis-x86_64/archive/b0333fa157debe1eb30c18033aae36b8f0dcc66e.tar.gz";
      hash = "sha256-pVSczkVxHBJ6G39PqcuwRlPSdZnl3pOyLoFnud1nzCY=";
    };
  }
  {
    name = "zig_yaml-0.2.0-C1161pmrAgC_rL9WzjvgNg7HnmyAMwHsG3Sre0F4haPI";
    path = fetchzip {
      url = "https://github.com/kubkon/zig-yaml/archive/refs/tags/0.2.0.tar.gz";
      hash = "sha256-c9fbOdvuC6gGSlbRrppXYB6xh5YZJkTokLL9lD2g+Xs=";
    };
  }
]
